<a href="https://colab.research.google.com/github/AnusreeChittineni/VAIL_2021/blob/main/Upsampling_Transpose_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### How to Use the UpSampling2D Layer


In [12]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import UpSampling2D
import numpy as np

In [17]:
# define input data
X = np.asarray([[1, 2],
			 [3, 4]])

# show input data for context
print(X)
X.shape

[[1 2]
 [3 4]]


(2, 2)

In [18]:
# reshape input data into one sample a sample with a channel
X = X.reshape((1, 2, 2, 1))
print(X)

[[[[1]
   [2]]

  [[3]
   [4]]]]


In [19]:
# define model
model = Sequential()
model.add(UpSampling2D(input_shape=(2, 2, 1)))

# summarize the model
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
up_sampling2d_3 (UpSampling2 (None, 4, 4, 1)           0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


In [22]:
# make a prediction with the model
yhat = model.predict(X)

In [23]:
# reshape output to remove channel to make printing easier
yhat = yhat.reshape((4, 4))

# summarize output
# each row and column is doubled 
print(yhat)

[[1. 1. 2. 2.]
 [1. 1. 2. 2.]
 [3. 3. 4. 4.]
 [3. 3. 4. 4.]]


In [32]:
# example of using different scale factors for each dimension

# define model
model_2 = Sequential()
model_2.add(UpSampling2D(size=(2, 3), input_shape=(2,2,1)))

# summarize the model
model_2.summary()

# make a prediction with the model
yhat_2 = model_2.predict(X)

# summarize output
# each row is doubled and each column is tripled 
print(yhat_2)

Model: "sequential_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
up_sampling2d_10 (UpSampling (None, 4, 6, 1)           0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
[[[[1.]
   [1.]
   [1.]
   [2.]
   [2.]
   [2.]]

  [[1.]
   [1.]
   [1.]
   [2.]
   [2.]
   [2.]]

  [[3.]
   [3.]
   [3.]
   [4.]
   [4.]
   [4.]]

  [[3.]
   [3.]
   [3.]
   [4.]
   [4.]
   [4.]]]]


In [34]:
# example of using bilinear interpolation when upsampling

# define model
model_3 = Sequential()
model_3.add(UpSampling2D(interpolation='bilinear', input_shape=(2,2,1)))

# summarize the model
model_3.summary()

# make a prediction with the model
yhat_3 = model_3.predict(X)

# summarize output
print(yhat_3)

Model: "sequential_12"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
up_sampling2d_12 (UpSampling (None, 4, 4, 1)           0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
[[[[1.  ]
   [1.25]
   [1.75]
   [2.  ]]

  [[1.5 ]
   [1.75]
   [2.25]
   [2.5 ]]

  [[2.5 ]
   [2.75]
   [3.25]
   [3.5 ]]

  [[3.  ]
   [3.25]
   [3.75]
   [4.  ]]]]


### Simple Generator Model With the UpSampling2D Layer


In [37]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Reshape
from tensorflow.keras.layers import UpSampling2D
from tensorflow.keras.layers import Conv2D

In [38]:
# example of using upsampling in a simple generator model

# define model
model_4 = Sequential()
# define input shape, output enough activations for for 128 5x5 image
model_4.add(Dense(128 * 5 * 5, input_dim=100))
# reshape vector of activations into 128 feature maps with 5x5
model_4.add(Reshape((5, 5, 128)))
# double input from 128 5x5 to 1 10x10 feature map
model_4.add(UpSampling2D())
# fill in detail in the upsampled feature maps and output a single image
model_4.add(Conv2D(1, (3,3), padding='same'))
# summarize model
model_4.summary()

Model: "sequential_14"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 3200)              323200    
_________________________________________________________________
reshape_1 (Reshape)          (None, 5, 5, 128)         0         
_________________________________________________________________
up_sampling2d_14 (UpSampling (None, 10, 10, 128)       0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 10, 10, 1)         1153      
Total params: 324,353
Trainable params: 324,353
Non-trainable params: 0
_________________________________________________________________


### How to Use the Conv2DTranspose Layer

In [39]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2DTranspose

In [40]:
# example of using the transpose convolutional layer

# define model
model_5 = Sequential()
model_5.add(Conv2DTranspose(1, (1,1), strides=(2,2), input_shape=(2, 2, 1)))
# summarize the model
model_5.summary()
# define weights that they do nothing
weights = [asarray([[[[1]]]]), asarray([0])]
# store the weights in the model
model_5.set_weights(weights)
# make a prediction with the model
yhat_5 = model_5.predict(X)
# reshape output to remove channel to make printing easier
yhat_5 = yhat_5.reshape((4, 4))
# summarize output
print(yhat_5)

Model: "sequential_15"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_transpose (Conv2DTran (None, 4, 4, 1)           2         
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________
[[1. 0. 2. 0.]
 [0. 0. 0. 0.]
 [3. 0. 4. 0.]
 [0. 0. 0. 0.]]


### Simple Generator Model With the Conv2DTranspose Layer


In [41]:
# define model
model_6 = Sequential()
# define input shape, output enough activations for for 128 5x5 image
model_6.add(Dense(128 * 5 * 5, input_dim=100))
# reshape vector of activations into 128 feature maps with 5x5
model_6.add(Reshape((5, 5, 128)))
# double input from 128 5x5 to 1 10x10 feature map
model_6.add(Conv2DTranspose(1, (3,3), strides=(2,2), padding='same'))
# summarize model
model_6.summary()

Model: "sequential_16"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 3200)              323200    
_________________________________________________________________
reshape_2 (Reshape)          (None, 5, 5, 128)         0         
_________________________________________________________________
conv2d_transpose_1 (Conv2DTr (None, 10, 10, 1)         1153      
Total params: 324,353
Trainable params: 324,353
Non-trainable params: 0
_________________________________________________________________
